_Since b0.6.10_

== Compilers
See link:Compilers#using-magic-comments-to-specify-the-compiler-for-new-run-configurations[Using magic comments to specify the compiler for new run configurations].

== Root file

If TeXiFy does not guess your root file(s) correctly, you can help TeXiFy by using the `root` magic comment to point TeXiFy to a root file.
For example, use `%! root = main.tex` in a file that is included by `main.tex`, when TeXiFy cannot figure out that `main.tex` is a root file of this file.


== Language injection

See link:Language-injection[Language injection].

== Custom preamble for math and tikz preview

See link:Preview[Preview].

== Switching parser off and on

If you want to temporarily switch off the parser for a part of your LaTeX, for example because there is a parse error which is causing other problems in your files, you can use the magic comments `%! parser = off` and `%! parser = on` to avoid parsing the text between these two comments.
The syntax `% !TeX parser = off` is also supported.