See https://github.com/Ruben-Sten/TeXiFy-IDEA/blob/master/CONTRIBUTING.md for the general contributing guide.

== Debugging performance issues

If you do not have a favourite profiler yet, you can use VisualVM. Install it using your package manager or go to https://visualvm.github.io/.

* First, just run TeXiFy like usual.
* Start VisualVM.
* In the Applications panel on the left, identify the instance of IntelliJ where TeXiFy is running, probably it is named Idea. Right-click on it and open.
* Go to the Sampler tab.
* Click Settings, and click Profile only packages. Specify `nl.hannahsten.**` or a specific class you want to filter on. Note that if you want to filter for a Kotlin class you have to append `Kt` to the class name, e.g. `nl.hannahsten.texifyidea.editor.UpDownAutoBracketKt`. However, not all classes will appear in the view.
* Click CPU to start profiling, you can take a Snapshot to view and save results. Note that you may have to click a few more levels open to see the actual methods.
* To clear the profiling view, close and reopen the tab.

== Editing a lexer

When you edit a `.flex` file, regenerate the lexer with Run JFlex Generator from the context menu, as described at https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/lexer_and_parser_definition.html#generate-a-lexer-class

== LatexCommands.commandToken.text vs LatexCommands.name

Throughout the code, you may see either `LatexCommands.commandToken.text` or `LatexCommands.name` being used to get the command name (e.g. `\section`).
Since the (generated) implementation of `getName()` is

[source,java]
----
default String getName() {
    return getCommandToken().getText();
}
----

you would think that these are the same.
But there is an important difference! The `name` is _indexed_ (see `LatexCommandsIndex`).
This means that probably using `name` is recommended, as it would use the index, but it may be completely wrong if the index is not updated correctly.
This can lead to strange behaviour (see e.g. https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/1097[#1097]).
