This is a list of all the errors and warnings that are in Appendix B of _The Latex Companion_ <<mittelbach2004>>, plus some more we encountered while error/warning hunting.
For each error/warning, we give a minimal working example, and the relevant part of the output log.
For more info on a message, see <<mittelbach2004>>.
Used by us for testing purposes, written down here for future reference.

The logs here are when using `-file-line-error` flag when compiling.

== Errors

=== calc: `<character>' invalid at this point.

[source,latex,linenums]
----
\docmentclass{article}

\usepackage{calc}

\newcounter{error}
\setcounter{error}{3}
\setcounter{error}{\value{error} & 2}
----

----
./errors.tex:7: Package calc Error: `&' invalid at this point.
----

=== amsfonts: <command> allowed only in math mode
[source, latex, numlines]
----
\documentclass{article}

\usepackage{amsfonts}

\begin{document}
    \mathbb{A}
\end{document}
----

----
./errors.tex:6: LaTeX Error: \mathbb allowed only in math mode.
----

=== <name> undefined
[source, latex, numlines]
----
\documentclass{article}

\renewcommand{\bloop}{nothing}

\begin{document}
    \bloop
\end{document}
----

----
./errors.tex:3: LaTeX Error: Command \bloop undefined.
----

=== \< in mid line
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \begin{tabbing}
        One \= Two \\
        1 \> \< 2 \\
    \end{tabbing}
\end{document}
----

----
./errors.tex:6: LaTeX Error: \< in mid line.
----

=== A <Box> was supposed to be here
[source, latex, numlines]
----
\documentclass{article}

\newcommand{\mybox}

\begin{document}
    \sbox{\mybox}{0}
\end{document}
----

----
./errors.tex:4: A <box> was supposed to be here.
----

=== textcomp: Accent <command> not provided by font family <name>
[source, latex, numlines]
----
\documentclass{article}

\usepackage{mathpazo}
\usepackage{textcomp}

\begin{document}
    \textuparrow
\end{document}
----

----
./errors.tex:7: Package textcomp Error: Symbol \textuparrow not provided by
(textcomp)                font family ppl in TS1 encoding.
(textcomp)                Default family used instead.
----

=== Argument of <command> has an extra }
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \fbox}
\end{document}
----

----
./errors.tex:4: Argument of \fbox  has an extra }.
----

=== Bad \line or \vector argument
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \line(1,1){-1}
\end{document}
----

----
./errors.tex:4: LaTeX Error: Bad \line or \vector argument.
----

=== Bad math environment delimiter
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \]
\end{document}
----

----
./errors.tex:4: LaTeX Error: Bad math environment delimiter.
----

=== Bad register code (<code>)
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
hallo
\sbox{\textwidth}{box}
\end{document}
----

----
./errors.tex:5: Bad register code (23592960).
----

=== \begin{<env>} ended by \end{<other env>}
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \end{centering}
\end{document}
----

----
./errors.tex:4: LaTeX Error: \begin{document} ended by \end{centering}.
----

=== amsmath: \begin{split} won't work here
[source, latex, numlines]
----
\documentclass{article}

\usepackage{amsmath}

\begin{document}
    \begin{split}
        \pi
    \end{split}
\end{document}
----

----
./errors.tex:8: Package amsmath Error: \begin{split} won't work here.
----

=== Can be used only in preamble
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \begin{document}
    \end{document}
\end{document}
----

----
./errors.tex:4: LaTeX Error: Can be used only in preamble.
----

=== Cannot be used in preamble
[source, latex, numlines]
----
\documentclass{article}

\nocite{magic}

\begin{document}
\end{document}
----

----
./errors.tex:3: LaTeX Error: Cannot be used in preamble.
----

=== graphicx/graphics: Cannot determine size of graphic in <file>
Compile with pdflatex and `-output-format=dvi`

[source, latex, numlines]
----
\documentclass{article}

\usepackage{graphicx}

\begin{document}
    \includegraphics{figures/background-black-cat.jpg}
\end{document}
----

----
./errors.tex:6: LaTeX Error: Cannot determine size of graphic in figures/backgr
ound-black-cat.jpg (no BoundingBox).
----

=== graphicx/graphics: Cannot include graphics of type: <ext>
[source, latex, numlines]
----
\documentclass{article}

\usepackage{graphicx}

\begin{document}
    \includegraphics[type=tex]{figures/background-black-cat.jpg}
\end{document}
----

----
./errors.tex:6: LaTeX Error: Can not include graphics of type: tex.
----

=== \caption outside float
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \caption{This is illegal.}
\end{document}
----

----
./errors.tex:4: LaTeX Error: \caption outside float.
----

=== Command <name> already defined
[source, latex, numlines]
----
\documentclass{article}

\newcommand{\documentclass}{hahaha}

\begin{document}
\end{document}
----

----
./errors.tex:3: LaTeX Error: Command \documentclass already defined.
----

=== Command <name> not defined as a math alphabet
[source, latex, numlines]
----
\documentclass{article}

\SetMathAlphabet{\methit}{normal}{OT1}{ppl}{m}{it}

\begin{document}
    $x$
\end{document}
----

----
./errors.tex:3: LaTeX Error: Command `\methit' not defined as a math alphabet.
----

=== Counter too large
[source, latex, numlines]
----
\documentclass{article}

\renewcommand{\theequation}{\alph{equation}}
\setcounter{equation}{27}

\begin{document}
    \theequation
\end{document}
----

----
./errors.tex:6: LaTeX Error: Counter too large.
----

=== Dimension too large
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \rule{16384pt}{2pt}
\end{document}
----

----
./errors.tex:5: Dimension too large.
----

=== amsmath: \displaybreak cannot be applied here
[source, latex, numlines]
----
\documentclass{article}

\usepackage{amsmath}

\begin{document}
    \[
        \begin{aligned}
            x \displaybreak y
        \end{aligned}
    \]
\end{document}
----

----
./errors.tex:8: Package amsmath Error: \displaybreak cannot be applied here.
----

=== graphicx/graphics: Division by 0
[source, latex, numlines]
----
\documentclass{article}

\usepackage{graphicx}

\begin{document}
    \includegraphics[angle=-90,height=3cm]{figures/background-black-cat.jpg}
\end{document}
----

----
./errors.tex:6: Package graphics Error: Division by 0.
----

=== Double subscript
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    $x_i_2$
\end{document}
----

----
./errors.tex:4: Double subscript.
l.4     $x_i_
             2$
----

=== Encoding scheme <name> unknown
[source, latex, numlines]
----
\documentclass{article}

\usepackage[15]{fontenc}

\begin{document}
    text
\end{document}
----

----
/home/abby/texlive/2019/texmf-dist/tex/latex/base/fontenc.sty:104: Package font
enc Error: Encoding file `15enc.def' not found.
(fontenc)                You might have misspelt the name of the encoding.

/home/abby/texlive/2019/texmf-dist/tex/latex/base/fontenc.sty:105: LaTeX Error:
 Encoding scheme `15' unknown.

./errors.tex:5: LaTeX Error: Encoding scheme `15' unknown.
----

=== Environment <name> undefined
[source, latex, numlines]
----
\documentclass{article}

\renewenvironment{bla}{a}{b}

\begin{document}
\end{document}
----

----
./errors.tex:3: LaTeX Error: Environment bla undefined.
----

=== amsmath: Erroneous nesting of equation structures
[source, latex, numlines]
----
\documentclass{article}

\usepackage{amsmath}

\begin{document}
    \begin{align}
        \begin{align}
            x
        \end{align}
    \end{align}
\end{document}
----

----
./errors.tex:10: Package amsmath Error: Erroneous nesting of equation structure
s;
(amsmath)                trying to recover with `aligned'.
----

=== Extra alignment tab has been changed to \cr
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \begin{tabular}{2}
        1 & 2 & 3 \\
    \end{tabular}
\end{document}
----

----
./errors.tex:5: Extra alignment tab has been changed to \cr.
<recently read> \endtemplate

l.5         1 & 2 &
                    3 \\
----

=== Extra \endgroup
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \end{centering}
\end{document}
----

----
./errors.tex:4: Extra \endgroup.
----

=== Extra \or
[source, latex, numlines]
----
\documentclass{article}

\or
----

----
./main.tex:3: Extra \or.
l.3 \or
----

=== Extra \right
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    $(\right)$
\end{document}
----

----
./main.tex:4: Extra \right.
l.4     $(\right)
                 $
----

=== Extra }, or forgotten $
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    $x}$
\end{document}
----

----
./main.tex:4: Extra }, or forgotten $.
l.4     $x}
           $
----

=== Extra }, or forgotten \endgroup
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \begin{center}
        text}
    \end{center}
\end{document}
----

----
./main.tex:5: Extra }, or forgotten \endgroup.
l.5         text}
----

=== File `<name>' not found
[source, latex, numlines]
----
\documentclass{article}

\begin{document}
    \input{fakenews.tex}
\end{document}
----

----
! LaTeX Error: File `fakenews.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name:
./main.tex:4: Emergency stop.
<read *>

l.4     \input{fakenews.tex}

./main.tex:4:  ==> Fatal error occurred, no output PDF file produced!
----

=== Float(s) lost
[source, latex, numlines]
----
\documentclass{article}
\usepackage{graphicx}

\begin{document}
    \footnote{\begin{figure}
                  \includegraphics{figures/cat.tikz}
    \end{figure}}
\end{document}
----

----
./main.tex:8: LaTeX Error: Float(s) lost.
----

=== Font family <cdp>+<family> unknown
[source, latex, numlines]
----
\documentclass{article}

\DeclareFontShape{T1}{bla}{}{}{}{}
----

----
./main.tex:3: LaTeX Error: Font family `T1+bla' unknown.
----


== Warnings



=== Citation `<key>' on page <number> undefined

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    \cite{key}
\end{document}
----

----
LaTeX Warning: Citation `key' on page 1 undefined on input line 4.

LaTeX Warning: There were undefined references.
----

=== Command <name> invalid in math mode

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    $รถ$
\end{document}
----

----

LaTeX Warning: Command \" invalid in math mode on input line 4.

./errors.tex:4: Please use \mathaccent for accents in math mode.
\add@accent ...@spacefactor \spacefactor }\accent
                                                  #1 #2\egroup \spacefactor ...
l.4     $รถ
           $
./errors.tex:4: You can't use `\spacefactor' in math mode.
\add@accent ...}\accent #1 #2\egroup \spacefactor
                                                  \accent@spacefactor
l.4     $รถ
           $
----

=== Empty `thebibliography' environment

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    \begin{thebibliography}{}
    \end{thebibliography}
\end{document}
----

----
LaTeX Warning: Empty `thebibliography' environment on input line 5.
----

=== (\end occurred inside a group at level <number)

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    {
\end{document}
----

----
(\end occurred inside a group at level 1)

### simple group (level 1) entered at line 4 ({)
### bottom level
----

=== (\end occurred when <condition> on line <line number> was incomplete)

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    \include{included}
\end{document}
----

[source,latex,linenums]
----
\end{document}
----

----
(\end occurred when \iftrue on line 4 was incomplete)
(\end occurred when \ifnum on line 4 was incomplete)
----

=== File `<name>' already exists on the system. Not generating it from this source

[source,latex,linenums]
----
\documentclass{article}
\begin{document}
    \begin{filecontents}{included.tex}
    \end{filecontents}
\end{document}
----

----
LaTeX Warning: File `included.tex' already exists on the system.
               Not generating it from this source.
----

=== Float too large for page by <value>

[source,latex,linenums]
----
\documentclass{article}
\usepackage{graphicx}
\begin{document}
    \begin{figure}
        \begin{center}
            \includegraphics[width=\textwidth]{fig.pdf}
            \caption[Short caption]{Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text}
        \end{center}
    \end{figure}
\end{document}
----

----
LaTeX Warning: Float too large for page by 5.92273pt on input line 9.
----

=== Font shape <font shape> in size <size> not available

[source,latex,linenums]
----
\documentclass{article}
\begin{document}
    \fontsize{42pt}{50pt}
    Text.
\end{document}
----

----
LaTeX Font Warning: Font shape `OT1/cmr/m/n' in size <42> not available
(Font)              size <24.88> substituted on input line 5.

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 17.12pt have occurred.
----

=== Font shape <font shape> undefined. Using `<other shape>' instead

[source,latex,linenums]
----
\documentclass{article}
\begin{document}
    \fontseries{b}\ttfamily Text.
\end{document}
----

----
LaTeX Font Warning: Font shape `OT1/cmtt/b/n' undefined
(Font)              using `OT1/cmtt/m/n' instead on input line 3.

LaTeX Font Warning: Some font shapes were not available, defaults substituted.
----

=== amsmath: Foreign command <command>; \frac or \genfrac should be used instead

[source,latex,linenums]
----
\documentclass{article}
\usepackage{amsmath}
\begin{document}
    $\primfrac{}{}$
\end{document}
----

----
Package amsmath Warning: Foreign command \;
(amsmath)                \frac or \genfrac should be used instead
(amsmath)                 on input line 4.
----

=== Form feed has been converted to Blank Line

[source,latex,linenums]
----
\documentclass{article}
\begin{document}
    \begin{filecontents}{filecontents.tex}

    \end{filecontents}
\end{document}
----

----
LaTeX Warning: Writing file `./filecontents.tex'.


LaTeX Warning: Writing text `    ' before \end{filecontents}
               as last line of filecontents.tex on input line 5.


LaTeX Warning: Form Feed has been converted to Blank Line.
----

=== `h' float specifier changed to `ht'

[source,latex,linenums]
----
\documentclass{article}
\usepackage{graphicx}
\begin{document}
    \begin{figure}[h]
        \includegraphics{fig.pdf}
    \end{figure}
\end{document}
----

----
Overfull \hbox (252.50682pt too wide) in paragraph at lines 5--6
[][]

LaTeX Warning: Float too large for page by 295.04504pt on input line 6.


LaTeX Warning: `h' float specifier changed to `ht'.
----

=== Ignoring text `<text>' after \end{<env>}

[source,latex,linenums]
----
\begin{filecontents}{filecontents2.tex}
\end{filecontents} Text.
\documentclass{article}
\begin{document}
    Text.
\end{document}
----

----
LaTeX Warning: Writing file `./filecontents2.tex'.


LaTeX Warning: Ignoring text ` Text.' after \end{filecontents} on input line 2.
----

=== Label `<key>' multiply defined

[source,latex,linenums]
----
\documentclass{article}
\begin{document}
    Text.
    \label{mylabel}
    Text.
    \label{mylabel}
\end{document}
----

----
LaTeX Warning: Label `mylabel' multiply defined.

LaTeX Warning: There were multiply-defined labels.
----

=== Label(s) may have changed. Rerun to get cross-references right

[source,latex,linenums]
----
% https://tex.stackexchange.com/a/169245/98850
\documentclass{article}

\makeatletter

\begin{document}
\providecommand\r@foo{{1}{1}}
\edef\@currentlabel{.\expandafter\@firstoftwo\r@foo}
\label{foo}
a

\end{document}
----

----
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
----

=== Loose \hbox (badness <number>) <somewhere>

[source,latex,linenums]
----
% https://tex.stackexchange.com/q/496596/98850
\documentclass{article}

\begin{document}
    \hbadness=-1 % to report the badness
    \spaceskip.3333em \rightskip0pt plus20pt % allow only 20pt of stretchability
    \def\text{The badness of this line is 1000.}
    \setbox0=\hbox{\text}
    \hsize=\wd0 \advance\hsize by 0.1pt \noindent\text\break
    \end
    Text.
\end{document}
----

----
Loose \hbox (badness 0) in paragraph at lines 9--12
\OT1/cmr/m/n/10 The badness of this line is 1000.
----

=== Marginpar on page <number> moved

[source,latex,linenums]
----
\documentclass{article}

\begin{document}
    \marginpar{Text.} \marginpar{Text.}
\end{document}
----

----
LaTeX Warning: Marginpar on page 1 moved.


LaTeX Warning: Marginpar on page 1 moved.
----

=== Missing character: There is no <char> in font <name>!

[source,latex,linenums]
----

----

----

----

[bibliography]
== References
- [[[mittelbach2004, 1]]] Frank Mittelbach, Michel Goossens, Johannes Braams, and Chris Rowley. 2004. _The Latex Companion. 2nd ed._ Boston: Addison-Wesley.