:experimental:

These settings can be found in menu:File[Settings > Languages & Frameworks > TeXiFy]

[#soft-wraps]
== Option to enable use of soft wraps when opening LaTeX files

When enabled, soft wraps will always be used when opening LaTeX files.
Note you have to reopen files for this setting to take effect.

Soft wraps make sure that when a line does not fit in the window, it will be wrapped.

[#closing-math]
== Option to disable automatic insertion of second $

By default, when you type `$` to start an inline math environment, the closing `$` will be inserted automatically.
You can use this setting to disable this.

Note that if your cursor is right before the closing `$`, so like `$ <cursor>$`, you can type `$` and IntelliJ will skip over the closing `$` just like with closing braces.

[#brace-insertion]
== Option to disable automatic brace insertion around text in subscript and superscript

By default, TeXiFy will automatically insert braces around multiple letters/numbers when they are directly after a `_` or `^` without spaces inbetween.

This means that when you type `$a_bc$` it will result in `$a_{bc}$`, to ensure that both the `b` and the `c` appear as subscript.

You can disable this behaviour using this setting.

[#item-insertion]
== Option to disable auto-insertion of \item

By default, when you press kbd:[Enter] when in an itemize or enumerate environment, TeXiFy will insert a new `\item` for you.

For example, when in a situation like

[source,latex]
----
\begin{itemize}
    \item <cursor>
\end{itemize}
----

and you press kbd:[Enter], it will result in

[source,latex]
----
\begin{itemize}
    \item
    \item <cursor>
\end{itemize}
----

If you do not want to insert an `\item`, press kbd:[Shift + Enter] instead.

You can disable the automatic insertion of `\item` using this setting.

[#smart-quotes]
== Option to enable smart quote substitution

Instead of writing opening and closing quotes like `+`quote'+` and ```quote''` yourself, you can also let TeXiFy choose for you whether to insert opening or closing quotes, and of what type.

There are three options.

=== Ligatures

If you type single quotes, so you type `'quote'`, the opening single quote will be replaced by ```, so the result is `+`quote'+`.

For double quotes, typing `"quote"` will end up as ```quote''`.

=== Commands

Instead of using ``` for opening and `'` for closing, you can also use the commands `\lq{}` and `\rq{}` for left and right quotes.
These have exactly the same result.

Typing `'quote'` will result in `\lq{}quote\rq{}`, and typing `"quote"` will result in `\lq\lq{}quote\rq\rq{}`.

=== Csquotes
_Since b0.6.6_

The https://ctan.org/pkg/csquotes?lang=en[csquotes] (Context Sensitive quotes) package provides some improvements for typesetting quotes, using the `\enquote` command.
For example, nested quotations work properly.

Typing `'quote'` will result in `\enquote*{quote}` and typing `"quote"` will result in `\enquote{quote}`.

This also works for nested quotes, typing `"nested "quotes""` results in `\enquote{nested \enquote{quotes}}`.

Note that instead of typing the closing `'` or `"` you could also type the closing `}` and IntelliJ will skip over it like usual.

For more advantages, see https://tex.stackexchange.com/questions/39285/whats-the-advantage-of-using-csquotes-over-using-an-editors-auto-replacement-f

[#compiler-compatibility]
== Option to change compiler for which to check compatibility

In some cases, certain LaTeX can be valid when using one compiler but incorrect when using another.
For these cases, you can change the compiler to which your LaTeX is validated.
The inspections for which this is relevant have a quickfix which opens this settings page.

[#continuous-preview]
== Option to enable continuous preview of math and TikZ environments
_Since b0.6.7_

When enabled and you are typing in a math environment (for example inline math `$..$` or display math `\[ ... \]`) then a preview window will pop up which will show how the math will look like. The same holds for `tikzpicture` environments.

For more information about the preview and how to install dependencies, see link:Preview#Equation-preview[Equation preview].
For continuous compilation of the complete document, see link:Compilers#Latexmk[Latexmk].]