== Add label defining command to list
== Change `equation*/displaymath` environment to `\[..\]`
== Change to `\left..\right`
== Convert to other math environment
== [[move-section-to-file]]Move section contents to separate file
Similar to link:Intentions#selection-to-file[Move selection contents to separate file], except that it is triggered on
a section heading. Any `\section{...}` command will trigger this. It turns

.main.tex
[source,latex]
----
\documentclass{article}

\begin{document}
    \section{One}
    First section.
\end{document}
----

into the two files

.main.tex
[source,latex]
----
\documentclass{article}

\begin{document}
    \section{One}
    \input{one}
\end{document}
----

.one.tex
[source, latex]
----
First section.
----

== [[selection-to-file]]Move selection contents to separate file
Move the selected text to a new file. When triggering this intention, there will be a popup asking for the name and
location of the new file. Consider the following file:

.main.tex
[source,latex]
----
\documentclass{article}

\begin{document}
    This is a selected sentence.
\end{document}
----

Selecting the text "This is a selected sentence." will enable the intention. After triggering the inspection and naming
your new file `content.tex` we have the following two files

.main.tex
[source, latex]
----
\documentclass{article}

\begin{document}
    \input{content}
\end{document}
----

.content.tex
[source, latex]
----
This is a selected sentence.
----

== Split into multiple `\usepackage` commands



