:experimental:

=== [[table-creation-wizard]]Table Creation Wizard
_Since b0.6.6_

menu:Edit[LaTeX > Table Creation Wizard]

Displays a dialog with a table creation wizard with a table, caption, and label. Click the plus to add a column, the
minus to remove the column of the currently selected cell, and the pencil to edit this column.

Each column has a name, and a type.
The available column types are:

- Text: This is normal text, aligned left.
- Math: Use this to display math symbols in your table. All entries in this column will be enclosed in `$..$` when generating
LaTeX.
- Numbers: As per convention, numbers are aligned on the right.


=== [[clear-aux-files]]Clear Auxiliary Files

menu:Tools[LaTeX > Clear Auxiliary Files]

Searches the entire project, i.e., every folder in the project module, for auxiliary files and deletes them. The files with the following extensions are defined as auxiliary files:

[source, subs="verbatim"]
aux, bbl, bcf, brf, fls, idx, ind, lot, lot, nav, out, snm, toc

If auxiliary files in a certain directory do not get deleted, make sure you mark that directory as a source directory by right-clicking on it and selecting menu:Mark Directory as[Sources Root].