_Since b0.6.7_

When the makeindex setting in the run configuration is enabled, TeXiFy will handle makeindex for you.
Makeindex is only run when you actually include an index package like `imakeidx`.

Makeindex will be run as a separate configuration, so you will see the output in a window next to your normal LaTeX output window.
When you use the `auxil/` or `out/` directories, makeindex will be run there and the `.ind` file will be copied next to your main file so that the index package can find it.

Note that when you use `imakeidx` but no `auxil/` or `out/` then imakeidx will handle makeindex itself. 

[NOTE]
If you use xindy but no `auxil/` or `out/` then in order to allow imakeidx to run xindy, you need to provide the `-shell-escape` custom compiler argument in the run configuration.

Example:

[source,latex]
----
\documentclass{article}
\usepackage{imakeidx}
\makeindex
\begin{document}
    Some random\index{random} text\index{text} which should be indexed\index{index}.
    \printindex
\end{document}
----

TeXiFy also supports using xindy (instead of makeindex) and a custom index name, for example:

[source,latex]
----
\documentclass{article}
\usepackage[xindy]{imakeidx}
\makeindex[name=myindex]
\begin{document}
    Some random\index[myindex]{random} text\index[myindex]{text} which should be indexed\index[myindex]{index}.

    \printindex[myindex]
\end{document}
----

See the imakeidx documentation at https://ctan.org/pkg/imakeidx for more details.