:experimental:

== About run configurations

See https://www.jetbrains.com/help/idea/creating-and-editing-run-debug-configurations.html

== Template run configurations

For the LaTeX run configuration you can change the default template.
This means you can choose for example your favourite compiler or pdf viewer in the template, and it will be used when a new run configuration is created.
Note that choosing a main file to compile in the template generally is not useful because it will be different for each new run config, and when creating a run config from context (like when using the gutter icon next to `\begin{document}`), it will be overwritten anyway.
In principle, all other settings in the run configuration you can configure in the template.

You can change the template on two levels, project and global level.

=== Changing the project run configuration template

When changing this template, only new run configurations created in that project will be affected.

Open the Run/Debug Configurations by clicking on the dropdown at the top and selecting Edit Configurations.
Then go to Templates, select LaTeX and edit it.
For more information, see https://www.jetbrains.com/help/idea/changing-default-run-debug-configurations.html

=== Changing the run configuration template for new projects

When changing this template, all new run configurations created in any new project will be affected.

Go to menu:File[Other Settings > Run configuration Templates for New Projects] and select LaTeX.

== Run configuration settings

=== Separate BibTeX run configuration
=== Choose compiler
=== Custom compiler path
=== Custom compiler arguments
=== Custom SumatraPDF path

See link:Running/SumatraPDF-support#Portable-SumatraPDF[(Windows) Choose a custom path to SumatraPDF]

=== Custom pdf viewer

In the Custom pdf viewer field you can specify the command for your favourite pdf viewer, so for example if the command is `okular somefile.pdf` then you can fill in `okular`  here.
If the pdf file is not the last argument, you can use the `{pdf}` placeholder, so `okular {pdf}`.

Then when you run the run configuration, when the compilation has finished the pdf will open in the viewer you specified.

If you don't want to open any pdf viewer for some reason, select the checkbox but leave the field empty.

=== Choose LaTeX source file to compile
=== (MiKTeX only) Set a custom path for auxiliary files

When using MiKTeX, this path will be passed to the `-aux-directory` flag for pdflatex, and similar for other compilers which support an auxiliary directory.

=== Set a custom path for output files

This path will be passed to the `-output-directory` for pdflatex, and similar for other compilers which support an output directory.

Make sure to _disable this when using BibTeX without MiKTeX_, otherwise bibtex won't be run correctly.
The exception to this is when you have changed your `openout_any` setting in TeX Live.

=== Choose output format
=== Choose BibTeX run configuration
=== Choose Makeindex run configuration

See link:Makeindex[Makeindex support].

=== Other tasks to run before the run configuration, including other run configurations or external tools