:experimental:

On Windows, TeXiFy supports SumatraPDF as a pdf viewer with forward and inverse search.

It can be downloaded from https://www.sumatrapdfreader.org/download-free-pdf-viewer.html.
If you know you are on a 64-bit system you can download the 64-bit build installer. If you have no idea, download the normal installer which is the top-most link.

== Shortcuts

The default shortcut for forward search in IntelliJ is kbd:[Ctrl + Alt + Shift + .].
The default shortcut for backward search in SumatraPDF is a double left mouse click.

== Explanation

=== Forward search
When your cursor is in IntelliJ and you have just compiled a document, you can look up which line in the pdf corresponds to the line your cursor is at by going in IntelliJ to the menu menu:Tools[LaTeX > SumatraPDF > Forward Search], or using the shortcut kbd:[Ctrl + Alt + Shift + .] which is listed there.
This shortcut can also be used to bring the SumatraPDF window in view when you recompiled a document but you do not see it.

=== Backward or inverse search

You can also do the reverse of the forward search lookup.
To configure this, the first time you have to press menu:Tools[LaTeX > SumatraPDF > Configure Inverse Search], this will update a setting in SumatraPDF.
You also have to do this every time after you update IntelliJ.

Now you can double left-click in SumatraPDF in a pdf you just compiled, and it should make your cursor go to the correct location in IntelliJ.

== Portable SumatraPDF
_Since b0.6.6_

There also is support for portable SumatraPDF installations, in case you cannot install use the normal installer for example if you do not have administrator rights.
Open your link:Run-configurations[run configuration], click Select custom SumatraPDF path and specify in the text field the folder which contains `SumatraPDF.exe`, either by editing the field or by clicking the folder icon on the right.
When you run the run configuration, SumatraPDF should open.

Note that to use forward and inverse search, the folder containing `SumatraPDF.exe` should be added to your PATH, or the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SumatraPDF.exe` should be set to the path to `SumatraPDF.exe`.