:experimental:

These settings can be found in menu:File[Settings > Editor > Code Style > LaTeX] and menu:File[Settings > Editor > Code Style > BibTeX] for LaTeX and BibTeX, respectively.
These settings will change the behaviour of the link:Formatter[formatter], triggered by pressing kbd:[Ctrl + Alt + L], or the behaviour of the editor.

== Common code style settings for both LaTeX and BibTeX

These settings are available for both LaTeX and BibTeX.

[#indent-size]
=== Indent size

Change the number of spaces to indent with in the *Tabs and Indents* tab.

[#hard-wrap]
=== Option to hard wrap LaTeX and BibTeX files

These options are in the *Wrapping* tab.

Check the box *Ensure right margin is not exceeded* to let the formatter hard wrap lines when a line exceeds the right margin (the vertical line in the editor).
Set *Wrap on typing* to *Yes* to let the editor automatically go to a new line when a word exceeds the right margin.

== LaTeX specific code style settings

These settings are only available for LaTeX.

[#indent-comment]
=== Option to start comment at the same indentation as normal text

This setting is in the *Code Generation* tab.

Press kbd:[Ctrl + /] to turn a line into a comment.
By default (*Line comment at first column* is checked), this will turn the line

[source, latex]
```
    This is a sentence.
```
into the comment

[source, latex]
```
%    This is a sentence.
```

Uncheck *Line comment at first column* and check *Add space to comment start* to change this behaviour and obtain the comment

[source, latex]
```
    % This is a sentence.
```

Note that this only changes the behaviour when *generating* a comment with kbd:[Ctrl + L], and that this setting has no influence on the formatting of comments.

[#section-newlines]
=== Specify number of blank lines before sectioning commands

These settings are in the *Blank Lines* tab.

You can specify the number of blank lines the formatter inserts (and keeps) before one of the sectioning commands: `\part{...}`, `\chapter{...}`, `\section{...}`, `\subsection{...}`, `\subsubsection{...}`, `\paragraph{...}`, and `\subparagraph{...}`.

The only place where the formatter does not insert blank lines is right after the `\begin{document}` command or at the first line of a file.

