:pygmentize:

== Non-escaped common math operators

[#math-functions-in-text]
== Math functions in `\text`
_Since b0.7.3_

Math functions using `\text{myoperator}` can be replaced by their dedicated function (`\myoperator`).

== Non-breaking spaces before references
== Ellipsis with `...` instead of `\ldots` or `\dots`
== Normal space after abbreviation

After an abbreviation like `e.g.` you should use a normal space instead of an end-of-sentence space, so use `e.g.\ this` instead of `e.g. this` (arguably you need to type `e.g., this` anyway). If you don't do this, LaTeX will interpret `e.g.` as the end of a sentence and thus insert a larger space.

== En dash in number ranges
== End-of-sentence space after sentences ending with capitals
== Use of `.` instead of `\cdot`

When multiplying numbers, use `\cdot` instead of `.`.

== Use of `x` instead of `\times`
== Grouped superscript and subscript
== Insert `\qedhere` in trailing displaymath environment
== Use the matching amssymb symbol for extreme inequalities
== Dotless versions of i and j must be used with diacritics
== Enclose high commands with `\leftX..\rightX`
== Citations must be placed before interpunction

Use `Sentence~\cite{knuth1990}.` and not `Sentence.~\cite{knuth1990}`

== Gather equations
Multiple display math equations (which are surrounded by `\[..\]`) can be grouped into the `gather` environment.

== Figure not referenced

_Since b0.6.6_

You should always reference your figures, otherwise you have figure floating around in your document with no connection to the text.
This is undesirable, because then it may not be clear why the figure is there.

Because figures float around (LaTeX determines the location automatically) you should never refer to figures as 'The figure below'.

This inspection includes a quick fix to safe delete the figure environment.

.Example file which triggers the inspection.
[source,latex]
----
\documentclass{article}

\begin{document}

    \begin{figure}
        A figuring float.
        \label{fig:not-referenced}
    \end{figure}

\end{document}
----