== Start sentences on a new line

In general we recommend starting every sentence on a new line, especially because this works nicer with version control systems, which work per line.
That also makes it more meaningful to reference a certain line in a document.
It also makes it easier to read when soft wrapping is off.

Note that this inspection would trigger on abbreviations like `etc.`.
However, when you use abbreviations like that you should always tell LaTeX to use a normal space instead of an end-of-sentence space, so instead of `This etc. contains a sentence` you should write ``This etc.\ contains a sentence`.
(Try it, the spaces are really different in the pdf!)

== Collapse cite commands

`\cite{knuth1990}\cite{goossens1993}` can be replaced with `\cite{knuth1990,goossens1993}`

== [[ins:eqref]] Use `\eqref{...}` instead of `(\ref{...})`
_Since b0.6.6_

Equations should be referenced using `\eqref{...}` rather than `(\ref{...})` to ensure that all your equation references
are formatted in the same way. This inspection is only triggered when the corresponding label was defined in a math environment.

== [[ins:documentclass]] File that contains a document environment should contain a `\documentclass` command
_Since b0.7.1_

When separating the preamble from the root LaTeX file, keep the `\documentclass` command in the root file.
To quote The LaTeX Companion:

> Commands placed between `\documentclass` and `\begin{document}` are in the so-called _document preamble_.

This implies that the `\documentclass` command itself is **not** part of the preamble.
When extracting the preamble, put it in a `personal.sty` (package) file, and include it in the root document with `\usepackage{personal}`.
When the need arises to specify the document class in the personal package, transform the package to a document class `personal.cls` and include it with `\documentclass{personal}`.
