== Might break TeXiFy functionality
== [[verbatim]]Verbatim environments might break TeXiFy
Using a verbatim environment, like `verbatim` or `lstlisting`, might break the parser.
The contents of a verbatim environment will often be touched by the formatter (they shouldn't).
This inspection warns you of this behaviour, and suggests two fixes:

- Surround the environment with `% @formatter:off` and `% @formatter:on` comments to link:Code-formatting[disable the formatter] in the environment.
This only fixes the formatting issues.
- Move the environment to a separate file.
A file that contains only a verbatim environment will not be touched by the formatter.
If the verbatim environment caused any parse errors in the original file, these will be resolved.
This fixes formatting issues in the verbatim environment, and parse errors in the original file.

== [[too-large-section]]Too large section

Similar to link:Intentions#selection-to-file[move selection contents to separate file] and link:Intentions#move-section-to-file[move section contents to separate file], except that this is a visible warning on a section command whenever a section is too large (currently some thousand characters).